### ISSUE TITLE
scene population

### ISSUE THREAD

**Issue by caichuang0415** [Genesis-Embodied-AI/RoboGen#25]
Thanks for sharing your wonderful work! 
I am eager to know where is the "scene population" codes in your project? It refers to the "text-to-image-to-3D generation" in your paper.
Could you please point out that part's codes for me? Thank you very much!

**Comment by yufeiwang63** [comment]
Hi,

Thanks for your interest in our work.
For most rigid and articulated object manipulation & locomotion tasks, we used retrieval-based scene population, i.e., the objects are retrieved from Objaverse. 
For soft body manipulation tasks, we used the text-to-image-to-3d generation pipeline. Since soft body dynamics is not supported in pybullet, in this reproducing codebase we did not try to integrate this text-to-image-to-3d pipeline with pybullet. 

However, if you are interested, we used this repo: https://github.com/ashawkey/stable-dreamfusion for image-2-3d generation. 

Also, I believe the text23d generation field is evolving rapidly so there should be many more new repos these days that can do even better & faster generation.
